---
title: Mapping Student Course Activity
authors: 
  - Amber Thomas
date: '2016-12-27'
slug: fccCourses
categories:
  - project
tags:
  - R
  - machine learning
  - data viz
description: 'Exploring the courses taken and performance of 103,091 Free Code Camp students.'
image: ''
imageAlt: ''
imageCredit: ''
imageCreditLink: ''
type: ''
disqus: 'true'
aliases:
  - /projects/2016/12/27/fcccourses/
---



<ul>
<li><a href="#introduction">Introduction</a></li>
<li><a href="#data-exploration">Data Exploration</a></li>
<li><a href="#feature-engineering">Feature Engineering</a></li>
<li><a href="#data-visualizations">Data Visualizations</a></li>
<li><a href="#conclusions">Conclusions</a></li>
<li><a href="#my-suggestions">My Suggestions:</a></li>
</ul>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p><a href="https://www.freecodecamp.com/">Free Code Camp</a> (FCC) is an online, self-paced, collection of massive open online courses (MOOCs) aimed at teaching users to code. Campers can log onto the service, complete coding challenges and projects, and earn certificates commemorating their completion. The topics covered include HTML5, CSS3, JavaScript, Databases, Git &amp; Github, Node.js, React.js, and D3.js.</p>
<p>In December of 2015, FCC released <a href="https://medium.freecodecamp.com/free-code-camp-christmas-special-giving-the-gift-of-data-6ecbf0313d62#.ibujuvlhc">lots of data</a> regarding the progress and solutions of their users throughout the courses. When I say lots, I mean there are data for over 100,000 students here!</p>
<p>Without having first looked at the dataset, the first questions I may consider are those posed by FCC itself:</p>
<ul>
<li>Can our campers be broken down into cohort groups based on challenge completion behavior?</li>
<li>Is there a challenge completion tempo that typifies high-achieving campers? One that typifies slow-and-steady campers?</li>
<li>Many campers will leave Free Code Camp for several months due to burnout, or life getting in the way, then return a few months later. Are there any meaningful patterns here?</li>
<li>What proportion of campers complete challenges mostly in order, as opposed to skipping around?</li>
<li>What proportion of campers dive directly into harder challenges, then work backward until they are able to start successfully completing challenges?</li>
<li>Are there any challenges that seem excessively hard, and require significantly more time investment than adjacent challenges?</li>
<li>Are there any challenges that are disproportionately popular, considering their later position within our curriculum?</li>
<li>Which challenges support the most diverse solutions?</li>
<li>Are campers more likely to use Object Oriented Programming solutions or Functional Programming solutions?</li>
</ul>
<p>That’s certainly a good place to start. I don’t think I’ll get to answer all of those in this project, but I’ll answer some.</p>
<p>Time to look at the data!</p>
<div id="importing-necessary-packages" class="section level3">
<h3>Importing Necessary Packages</h3>
<pre class="r"><code># For importing JSON data
library(tidyjson)
library(jsonlite)
library(data.table)

# For data manipulation and tidying
library(dplyr)
library(tidyr)
library(Hmisc)

# For data visualizations
library(ggplot2)
library(highcharter)
library(igraph)
library(networkD3)
library(htmlwidgets)

# For web scraping
library(rvest)
library(curl)

# For machine learning
library(caret)
library(ranger)
library(e1071)</code></pre>
</div>
</div>
<div id="data-exploration" class="section level2">
<h2>Data Exploration</h2>
<div id="importing-dataset" class="section level3">
<h3>Importing Dataset</h3>
<p>The data are freely available from FCC and can be downloaded <a href="http://academictorrents.com/details/030b10dad0846b5aecc3905692890fb02404adbf">here</a>. I’m going to import the data using the<code>jsonlite</code>, <code>tidyjson</code> and <code>data.table</code> packages.</p>
<p><em>Note: my poor little laptop couldn’t handle importing/binding these files. I am lucky enough that <a href="http://www.animoplex.com">Parker</a> let me use his animation rendering machine (i.e. work-horse in computer form) to complete this project.</em></p>
<pre class="r"><code># Import JSON using the jsonlite package
fcc &lt;- fromJSON(&quot;output.json&quot;, flatten = TRUE)</code></pre>
<p>Now we have a list of data frames. Time to bind them into a giant data frame using the <code>data.table</code> package.</p>
<pre class="r"><code>fcc_df &lt;- rbindlist(fcc, fill = TRUE, idcol = TRUE)</code></pre>
<p>Last thing is to convert the data.table to a data.frame (this one is in base R).</p>
<pre class="r"><code>fcc_df2 &lt;- as.data.frame(fcc_df)</code></pre>
</div>
<div id="data-structure-and-variables" class="section level3">
<h3>Data Structure and Variables</h3>
<p>Great! Now that our data is imported, we can get a look at it. I’ll start by looking at it’s structure.</p>
<pre class="r"><code>str(fcc_df2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    7236580 obs. of  4 variables:
##  $ .id          : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ name         : chr  &quot;Waypoint: Learn how Free Code Camp Works&quot; &quot;Waypoint: Learn how Free Code Camp Works&quot; &quot;Waypoint: Preview our Challenge Map&quot; &quot;Waypoint: Browse our Field Guide&quot; ...
##  $ completedDate: chr  &quot;1434650566196&quot; &quot;1434650582665&quot; &quot;1434651100007&quot; &quot;1434651311734&quot; ...
##  $ solution     : chr  NA NA NA NA ...</code></pre>
<p>Ok, so as expected, we are working with a data frame with 4 variables and <strong>7,236,580</strong> observations! No wonder my laptop couldn’t handle it.</p>
<p>Our 4 variables are:</p>
<ul>
<li><strong>.id</strong> : The ID number created when binding our list of data frames into a single data frame. In this case, it corresponds to FCC user number.</li>
<li><strong>name</strong> : The FCC course completed</li>
<li><strong>completedDate</strong> : The date the course was completed (as a Unix timestamp in milliseconds)</li>
<li><strong>solution</strong> :The user’s solution to the course challenge.</li>
</ul>
<p>While a character string is fine for the “solution” column, I’m going to change the data type of the name, id, and completedDate columns. Name and id should both be factors.</p>
<pre class="r"><code>fcc_df2$name &lt;- as.factor(fcc_df2$name)
fcc_df2$.id &lt;- as.factor(fcc_df2$.id)</code></pre>
<p>How many users are we dealing with?</p>
<pre class="r"><code>fcc_df2 %&gt;% summarise(n_distinct(.id))</code></pre>
<pre><code>##   n_distinct(.id)
## 1          103091</code></pre>
<p>103,091 different users!</p>
<p>How many challenges are there? And do we have any duplicates?</p>
<pre class="r"><code>levels(fcc_df2$name)</code></pre>
<pre><code>##   [1] &quot;&quot;                                                                          
##   [2] &quot;: Use the Javascript Console&quot;                                              
##   [3] &quot;: Using typeof&quot;                                                            
##   [4] &quot;Apply Angular.js Directives&quot;                                               
##   [5] &quot;Arguments Optional&quot;                                                        
##   [6] &quot;Basejump: Build a Nightlife Coordination App&quot;                              
##   [7] &quot;Basejump: Build a Pinterest Clone&quot;                                         
##   [8] &quot;Basejump: Build a Pintrest Clone&quot;                                          
##   [9] &quot;Basejump: Build a Voting App&quot;                                              
##  [10] &quot;Basejump: Chart the Stock Market&quot;                                          
##  [11] &quot;Basejump: Manage a Book Trading Club&quot;                                      
##  [12] &quot;Basejumps: Build a Nightlife Coordination App&quot;                             
##  [13] &quot;Basejumps: Build a Pinterest Clone&quot;                                        
##  [14] &quot;Basejumps: Build a Voting App&quot;                                             
##  [15] &quot;Basejumps: Chart the Stock Market&quot;                                         
##  [16] &quot;Basejumps: Manage a Book Trading Club&quot;                                     
##  [17] &quot;Binary Agents&quot;                                                             
##  [18] &quot;Bonfire: Arguments Optional&quot;                                               
##  [19] &quot;Bonfire: Binary Agents&quot;                                                    
##  [20] &quot;Bonfire: Boo who&quot;                                                          
##  [21] &quot;Bonfire: Check for Palindromes&quot;                                            
##  [22] &quot;Bonfire: Chunky Monkey&quot;                                                    
##  [23] &quot;Bonfire: Confirm the Ending&quot;                                               
##  [24] &quot;Bonfire: Convert HTML Entities&quot;                                            
##  [25] &quot;Bonfire: Diff Two Arrays&quot;                                                  
##  [26] &quot;Bonfire: DNA Pairing&quot;                                                      
##  [27] &quot;Bonfire: Drop it&quot;                                                          
##  [28] &quot;Bonfire: Everything Be True&quot;                                               
##  [29] &quot;Bonfire: Exact Change&quot;                                                     
##  [30] &quot;Bonfire: Factorialize a Number&quot;                                            
##  [31] &quot;Bonfire: Falsey Bouncer&quot;                                                   
##  [32] &quot;Bonfire: Falsy Bouncer&quot;                                                    
##  [33] &quot;Bonfire: Find the Longest Word in a String&quot;                                
##  [34] &quot;Bonfire: Finders Keepers&quot;                                                  
##  [35] &quot;Bonfire: Friendly Date Ranges&quot;                                             
##  [36] &quot;Bonfire: Inventory Update&quot;                                                 
##  [37] &quot;Bonfire: Make a Person&quot;                                                    
##  [38] &quot;Bonfire: Map the Debris&quot;                                                   
##  [39] &quot;Bonfire: Meet Bonfire&quot;                                                     
##  [40] &quot;Bonfire: Missing letters&quot;                                                  
##  [41] &quot;Bonfire: Mutations&quot;                                                        
##  [42] &quot;Bonfire: No repeats please&quot;                                                
##  [43] &quot;Bonfire: Pairwise&quot;                                                         
##  [44] &quot;Bonfire: Pig Latin&quot;                                                        
##  [45] &quot;Bonfire: Repeat a string repeat a string&quot;                                  
##  [46] &quot;Bonfire: Return Largest Numbers in Arrays&quot;                                 
##  [47] &quot;Bonfire: Reverse a String&quot;                                                 
##  [48] &quot;Bonfire: Roman Numeral Converter&quot;                                          
##  [49] &quot;Bonfire: Search and Replace&quot;                                               
##  [50] &quot;Bonfire: Seek and Destroy&quot;                                                 
##  [51] &quot;Bonfire: Slasher Flick&quot;                                                    
##  [52] &quot;Bonfire: Smallest Common Multiple&quot;                                         
##  [53] &quot;Bonfire: Sorted Union&quot;                                                     
##  [54] &quot;Bonfire: Spinal Tap Case&quot;                                                  
##  [55] &quot;Bonfire: Steamroller&quot;                                                      
##  [56] &quot;Bonfire: Sum All Numbers in a Range&quot;                                       
##  [57] &quot;Bonfire: Sum All Odd Fibonacci Numbers&quot;                                    
##  [58] &quot;Bonfire: Sum All Primes&quot;                                                   
##  [59] &quot;Bonfire: Symmetric Difference&quot;                                             
##  [60] &quot;Bonfire: Title Case a Sentence&quot;                                            
##  [61] &quot;Bonfire: Truncate a string&quot;                                                
##  [62] &quot;Bonfire: Validate US Telephone Numbers&quot;                                    
##  [63] &quot;Bonfire: Where art thou&quot;                                                   
##  [64] &quot;Bonfire: Where do I belong&quot;                                                
##  [65] &quot;Boo who&quot;                                                                   
##  [66] &quot;Browse our Field Guide&quot;                                                    
##  [67] &quot;Build a Cash Register&quot;                                                     
##  [68] &quot;Build a Contact List&quot;                                                      
##  [69] &quot;Build a Geolocation Angular App&quot;                                           
##  [70] &quot;Build a Landing Page with HTML&quot;                                            
##  [71] &quot;Build an Address Book&quot;                                                     
##  [72] &quot;Build an Adventure Game&quot;                                                   
##  [73] &quot;Build Rock Paper Scissors&quot;                                                 
##  [74] &quot;Build Web Apps with Express.js&quot;                                            
##  [75] &quot;Cash Register&quot;                                                             
##  [76] &quot;Check for Palindromes&quot;                                                     
##  [77] &quot;Chunky Monkey&quot;                                                             
##  [78] &quot;Confirm the Ending&quot;                                                        
##  [79] &quot;Convert HTML Entities&quot;                                                     
##  [80] &quot;Create Angular.js Services&quot;                                                
##  [81] &quot;Customize Angular.js Directives&quot;                                           
##  [82] &quot;Customize your Porfolio Page&quot;                                              
##  [83] &quot;Customize your Portfolio Page&quot;                                             
##  [84] &quot;Design a Layout with HTML&quot;                                                 
##  [85] &quot;Design Responsively with Bootstrap&quot;                                        
##  [86] &quot;Diff Two Arrays&quot;                                                           
##  [87] &quot;Discover Chrome&#39;s DevTools&quot;                                                
##  [88] &quot;DNA Pairing&quot;                                                               
##  [89] &quot;Drop it like it&#39;s hot&quot;                                                     
##  [90] &quot;Everything Be True&quot;                                                        
##  [91] &quot;Factorialize a Number&quot;                                                     
##  [92] &quot;Falsey Bouncer&quot;                                                            
##  [93] &quot;Find the Longest Word in a String&quot;                                         
##  [94] &quot;Finders Keepers&quot;                                                           
##  [95] &quot;Friendly Date Ranges&quot;                                                      
##  [96] &quot;Get Help the Hacker Way with RSAP&quot;                                         
##  [97] &quot;Get Set for Basejumps&quot;                                                     
##  [98] &quot;Get Set for Ziplines&quot;                                                      
##  [99] &quot;Get Started with Angular.js&quot;                                               
## [100] &quot;Get Started with jQuery&quot;                                                   
## [101] &quot;Harness Dynamic HTML&quot;                                                      
## [102] &quot;Inventory Update&quot;                                                          
## [103] &quot;Join Our Chat Room&quot;                                                        
## [104] &quot;Learn Basic Computer Science&quot;                                              
## [105] &quot;Learn Boolean Logic&quot;                                                       
## [106] &quot;Learn Computer Hardware&quot;                                                   
## [107] &quot;Learn Computer Networking&quot;                                                 
## [108] &quot;Learn Computer Security&quot;                                                   
## [109] &quot;Learn Control Flow&quot;                                                        
## [110] &quot;Learn how Free Code Camp Works&quot;                                            
## [111] &quot;Learn JavaScript For Loops&quot;                                                
## [112] &quot;Learn JavaScript While Loops&quot;                                              
## [113] &quot;Learn Loops&quot;                                                               
## [114] &quot;Learn Regular Expressions&quot;                                                 
## [115] &quot;Listen for jQuery Events&quot;                                                  
## [116] &quot;Make a Person&quot;                                                             
## [117] &quot;Manage Packages with NPM&quot;                                                  
## [118] &quot;Manage Source Code with Git&quot;                                               
## [119] &quot;Map the Debris&quot;                                                            
## [120] &quot;Meet Bonfire&quot;                                                              
## [121] &quot;Meet Other Campers in your City&quot;                                           
## [122] &quot;Missing letters&quot;                                                           
## [123] &quot;Mutations&quot;                                                                 
## [124] &quot;No repeats please&quot;                                                         
## [125] &quot;Pair Program on Bonfires&quot;                                                  
## [126] &quot;Pairwise&quot;                                                                  
## [127] &quot;Pig Latin&quot;                                                                 
## [128] &quot;Power Forms with Angular.js&quot;                                               
## [129] &quot;Preview our Challenge Map&quot;                                                 
## [130] &quot;Repeat a string repeat a string&quot;                                           
## [131] &quot;Return Largest Numbers in Arrays&quot;                                          
## [132] &quot;Reverse a String&quot;                                                          
## [133] &quot;Roman Numeral Converter&quot;                                                   
## [134] &quot;Search and Replace&quot;                                                        
## [135] &quot;Seek and Destroy&quot;                                                          
## [136] &quot;Slasher Flick&quot;                                                             
## [137] &quot;Smallest Common Multiple&quot;                                                  
## [138] &quot;Sorted Union&quot;                                                              
## [139] &quot;Space Out with CSS&quot;                                                        
## [140] &quot;Spinal Tap Case&quot;                                                           
## [141] &quot;Start a Node.js Server&quot;                                                    
## [142] &quot;Steamroller&quot;                                                               
## [143] &quot;Structure Angular.js Routes&quot;                                               
## [144] &quot;Style Text with CSS&quot;                                                       
## [145] &quot;Sum All Numbers in a Range&quot;                                                
## [146] &quot;Sum All Odd Fibonacci Numbers&quot;                                             
## [147] &quot;Sum All Primes&quot;                                                            
## [148] &quot;Symmetric Difference&quot;                                                      
## [149] &quot;Title Case a Sentence&quot;                                                     
## [150] &quot;Trigger jQuery Effects&quot;                                                    
## [151] &quot;Truncate a string&quot;                                                         
## [152] &quot;Try Camper News&quot;                                                           
## [153] &quot;Validate US Telephone Numbers&quot;                                             
## [154] &quot;Waypoint: Access Array Data with Indexes&quot;                                  
## [155] &quot;Waypoint: Add a Negative Margin to an Element&quot;                             
## [156] &quot;Waypoint: Add a Submit Button to a Form&quot;                                   
## [157] &quot;Waypoint: Add Alt Text to an Image for Accessibility&quot;                      
## [158] &quot;Waypoint: Add Borders Around your Elements&quot;                                
## [159] &quot;Waypoint: Add Different a Margin to Each Side of an Element&quot;               
## [160] &quot;Waypoint: Add Different Margins to Each Side of an Element&quot;                
## [161] &quot;Waypoint: Add Different Padding to Each Side of an Element&quot;                
## [162] &quot;Waypoint: Add Elements within your Bootstrap Wells&quot;                        
## [163] &quot;Waypoint: Add Font Awesome Icons all of our Buttons&quot;                       
## [164] &quot;Waypoint: Add Font Awesome Icons to all of our Buttons&quot;                    
## [165] &quot;Waypoint: Add Font Awesome Icons to our Buttons&quot;                           
## [166] &quot;Waypoint: Add Free Code Camp to your LinkedIn Profile&quot;                     
## [167] &quot;Waypoint: Add ID Attributes to Bootstrap Elements&quot;                         
## [168] &quot;Waypoint: Add Images to your Website&quot;                                      
## [169] &quot;Waypoint: Add New Properties to a JavaScript Object&quot;                       
## [170] &quot;Waypoint: Add Placeholder Text to a Text Field&quot;                            
## [171] &quot;Waypoint: Add Rounded Corners with a Border Radius&quot;                        
## [172] &quot;Waypoint: Add Two Numbers with JavaScript&quot;                                 
## [173] &quot;Waypoint: Add your JavaScript Slot Machine Slots&quot;                          
## [174] &quot;Waypoint: Adjust the Margin of an Element&quot;                                 
## [175] &quot;Waypoint: Adjusting the Padding of an Element&quot;                             
## [176] &quot;Waypoint: Apply Angular.js Directives&quot;                                     
## [177] &quot;Waypoint: Apply Angularjs Directives&quot;                                      
## [178] &quot;Waypoint: Apply the Default Bootstrap Button Style&quot;                        
## [179] &quot;Waypoint: Bring your JavaScript Slot Machine to Life&quot;                      
## [180] &quot;Waypoint: Browse Camper News&quot;                                              
## [181] &quot;Waypoint: Browse our Field Guide&quot;                                          
## [182] &quot;Waypoint: Build a Cash Register&quot;                                           
## [183] &quot;Waypoint: Build a Contact List&quot;                                            
## [184] &quot;Waypoint: Build an Address Book&quot;                                           
## [185] &quot;Waypoint: Build an Adventure Game&quot;                                         
## [186] &quot;Waypoint: Build JavaScript Objects&quot;                                        
## [187] &quot;Waypoint: Build Objects with Functional Classes&quot;                           
## [188] &quot;Waypoint: Build Objects with Prototypal Classes&quot;                           
## [189] &quot;Waypoint: Build Rock Paper Scissors&quot;                                       
## [190] &quot;Waypoint: Build Web Apps with Express.js&quot;                                  
## [191] &quot;Waypoint: Build Web Apps with Expressjs&quot;                                   
## [192] &quot;Waypoint: Call out Optional Actions with Button Info&quot;                      
## [193] &quot;Waypoint: Center Text with Bootstrap&quot;                                      
## [194] &quot;Waypoint: Change Text Inside an Element Using jQuery&quot;                      
## [195] &quot;Waypoint: Change Text with Click Events&quot;                                   
## [196] &quot;Waypoint: Change the Color of Text&quot;                                        
## [197] &quot;Waypoint: Change the CSS of an Element Using jQuery&quot;                       
## [198] &quot;Waypoint: Change the Font Size of an Element&quot;                              
## [199] &quot;Waypoint: Check Radio Buttons and Checkboxes by Default&quot;                   
## [200] &quot;Waypoint: Check the Length Property of a String Variable&quot;                  
## [201] &quot;Waypoint: Claim Your Back End Development Certificate&quot;                     
## [202] &quot;Waypoint: Claim Your Front End Development Certificate&quot;                    
## [203] &quot;Waypoint: Claim Your Full Stack Development Certificate&quot;                   
## [204] &quot;Waypoint: Clean up your form using Linebreaks&quot;                             
## [205] &quot;Waypoint: Clone an Element Using jQuery&quot;                                   
## [206] &quot;Waypoint: Comment out HTML&quot;                                                
## [207] &quot;Waypoint: Comment your JavaScript Code&quot;                                    
## [208] &quot;Waypoint: Commit to a Goal and a Nonprofit&quot;                                
## [209] &quot;Waypoint: Concatenate Arrays with concat&quot;                                  
## [210] &quot;Waypoint: Concatenate Strings with concat&quot;                                 
## [211] &quot;Waypoint: Condense arrays with reduce&quot;                                     
## [212] &quot;Waypoint: Configure your Code Portfolio&quot;                                   
## [213] &quot;Waypoint: Configure your Public Profile&quot;                                   
## [214] &quot;Waypoint: Construct JavaScript Objects with Functions&quot;                     
## [215] &quot;Waypoint: Constructing JavaScript Objects with Functions&quot;                  
## [216] &quot;Waypoint: Continue working with Node.js Servers&quot;                           
## [217] &quot;Waypoint: Continue working with Nodejs Servers&quot;                            
## [218] &quot;Waypoint: Convert JSON Data to HTML&quot;                                       
## [219] &quot;Waypoint: Count Backwards With a For Loop&quot;                                 
## [220] &quot;Waypoint: Create a Block Element Bootstrap Button&quot;                         
## [221] &quot;Waypoint: Create a Bootstrap Button&quot;                                       
## [222] &quot;Waypoint: Create a Bootstrap Headline&quot;                                     
## [223] &quot;Waypoint: Create a Bootstrap Row&quot;                                          
## [224] &quot;Waypoint: Create a Bulleted Unordered List&quot;                                
## [225] &quot;Waypoint: Create a Class to Target with jQuery Selectors&quot;                  
## [226] &quot;Waypoint: Create a Custom Heading&quot;                                         
## [227] &quot;Waypoint: Create a Form Element&quot;                                           
## [228] &quot;Waypoint: Create a GitHub Account and Join our Chat Rooms&quot;                 
## [229] &quot;Waypoint: Create a JavaScript Slot Machine&quot;                                
## [230] &quot;Waypoint: Create a Set of Checkboxes&quot;                                      
## [231] &quot;Waypoint: Create a Set of Radio Buttons&quot;                                   
## [232] &quot;Waypoint: Create a Text Field&quot;                                             
## [233] &quot;Waypoint: Create an Ordered List&quot;                                          
## [234] &quot;Waypoint: Create Angular.js Services&quot;                                      
## [235] &quot;Waypoint: Create Angularjs Services&quot;                                       
## [236] &quot;Waypoint: Create Bootstrap Wells&quot;                                          
## [237] &quot;Waypoint: Create Decimal Numbers with JavaScript&quot;                          
## [238] &quot;Waypoint: Customize Angular.js Directives&quot;                                 
## [239] &quot;Waypoint: Customize Angularjs Directives&quot;                                  
## [240] &quot;Waypoint: Customize your Portfolio Page&quot;                                   
## [241] &quot;Waypoint: Declare JavaScript Objects as Variables&quot;                         
## [242] &quot;Waypoint: Declare JavaScript Variables&quot;                                    
## [243] &quot;Waypoint: Declare String Variables&quot;                                        
## [244] &quot;Waypoint: Declaring JavaScript Objects as Variables&quot;                       
## [245] &quot;Waypoint: Delete HTML Elements&quot;                                            
## [246] &quot;Waypoint: Delete Properties from a JavaScript Object&quot;                      
## [247] &quot;Waypoint: Delete your jQuery Functions&quot;                                    
## [248] &quot;Waypoint: Disable an Element Using jQuery&quot;                                 
## [249] &quot;Waypoint: Discover Chrome DevTools&quot;                                        
## [250] &quot;Waypoint: Ditch Custom CSS for Bootstrap&quot;                                  
## [251] &quot;Waypoint: Divide one Decimal by Another with JavaScript&quot;                   
## [252] &quot;Waypoint: Divide One Number by Another with JavaScript&quot;                    
## [253] &quot;Waypoint: Duplicate Instances of Objects from a Constructor Function&quot;      
## [254] &quot;Waypoint: Fill in the Blank with Placeholder Text&quot;                         
## [255] &quot;Waypoint: Filter Arrays with filter&quot;                                       
## [256] &quot;Waypoint: Find Numbers with Regular Expressions&quot;                           
## [257] &quot;Waypoint: Find White Space with Regular Expressions&quot;                       
## [258] &quot;Waypoint: Find Whitespace with Regular Expressions&quot;                        
## [259] &quot;Waypoint: Finish working with Node.js Servers&quot;                             
## [260] &quot;Waypoint: Finish working with Nodejs Servers&quot;                              
## [261] &quot;Waypoint: Generate Random Fractions with JavaScript&quot;                       
## [262] &quot;Waypoint: Generate Random Whole Numbers with JavaScript&quot;                   
## [263] &quot;Waypoint: Generate Random Whole Numbers within a Range&quot;                    
## [264] &quot;Waypoint: Get Geolocation Data&quot;                                            
## [265] &quot;Waypoint: Get Help the Hacker Way with RSAP&quot;                               
## [266] &quot;Waypoint: Get JSON with the jQuery getJSON Method&quot;                         
## [267] &quot;Waypoint: Get Set for Basejumps&quot;                                           
## [268] &quot;Waypoint: Get Set for Bonfires&quot;                                            
## [269] &quot;Waypoint: Get Set for Ziplines&quot;                                            
## [270] &quot;Waypoint: Get Started with Angular.js&quot;                                     
## [271] &quot;Waypoint: Get Started with Angularjs&quot;                                      
## [272] &quot;Waypoint: Get Started with jQuery&quot;                                         
## [273] &quot;Waypoint: Give a Background Color to a Div Element&quot;                        
## [274] &quot;Waypoint: Give Each Element a Unique ID&quot;                                   
## [275] &quot;Waypoint: Give your JavaScript Slot Machine some stylish images&quot;           
## [276] &quot;Waypoint: Give your JavaScript Slot Machine some Stylish Images&quot;           
## [277] &quot;Waypoint: Harness Dynamic HTML&quot;                                            
## [278] &quot;Waypoint: Headline with the h2 Element&quot;                                    
## [279] &quot;Waypoint: House our page within a Bootstrap Container Fluid Div&quot;           
## [280] &quot;Waypoint: Import a Google Font&quot;                                            
## [281] &quot;Waypoint: Inform with the Paragraph Element&quot;                               
## [282] &quot;Waypoint: Inherit Styles from the Body Element&quot;                            
## [283] &quot;Waypoint: Invert Regular Expression Matches with JavaScript&quot;               
## [284] &quot;Waypoint: Iterate Odd Numbers With a For Loop&quot;                             
## [285] &quot;Waypoint: Iterate over Arrays with map&quot;                                    
## [286] &quot;Waypoint: Iterate with JavaScript For Loops&quot;                               
## [287] &quot;Waypoint: Iterate with JavaScript While Loops&quot;                             
## [288] &quot;Waypoint: Join a Campsite in Your City&quot;                                    
## [289] &quot;Waypoint: Join our Alumni Network and Commit to Your Goal&quot;                 
## [290] &quot;Waypoint: Join Our Chat Room&quot;                                              
## [291] &quot;Waypoint: Join our LinkedIn Alumni Network&quot;                                
## [292] &quot;Waypoint: Join Strings with join&quot;                                          
## [293] &quot;Waypoint: Label Bootstrap Buttons&quot;                                         
## [294] &quot;Waypoint: Label Bootstrap Wells&quot;                                           
## [295] &quot;Waypoint: Learn Basic Computer Science&quot;                                    
## [296] &quot;Waypoint: Learn Boolean Logic&quot;                                             
## [297] &quot;Waypoint: Learn Computer Hardware&quot;                                         
## [298] &quot;Waypoint: Learn Computer Networking&quot;                                       
## [299] &quot;Waypoint: Learn Computer Security&quot;                                         
## [300] &quot;Waypoint: Learn Control Flow&quot;                                              
## [301] &quot;Waypoint: Learn how Free Code Camp Works&quot;                                  
## [302] &quot;Waypoint: Learn how Script Tags and Document Ready Work&quot;                   
## [303] &quot;Waypoint: Learn JavaScript For Loops&quot;                                      
## [304] &quot;Waypoint: Learn JavaScript While Loops&quot;                                    
## [305] &quot;Waypoint: Learn Loops&quot;                                                     
## [306] &quot;Waypoint: Learn Regular Expressions&quot;                                       
## [307] &quot;Waypoint: Learn What to Do If You Get Stuck&quot;                               
## [308] &quot;Waypoint: Line up Form Elements Responsively with Bootstrap&quot;               
## [309] &quot;Waypoint: Link to External Pages with Anchor Elements&quot;                     
## [310] &quot;Waypoint: Listen for jQuery Events&quot;                                        
## [311] &quot;Waypoint: Make Circular Images with a Border Radius&quot;                       
## [312] &quot;Waypoint: Make Dead Links using the Hash Symbol&quot;                           
## [313] &quot;Waypoint: Make Images Mobile Responsive&quot;                                   
## [314] &quot;Waypoint: Make Instances of Objects with a Constructor Function&quot;           
## [315] &quot;Waypoint: Make Object Properties Private&quot;                                  
## [316] &quot;Waypoint: Make Unique Objects by Passing Parameters to our Constructor&quot;    
## [317] &quot;Waypoint: Manage Packages with NPM&quot;                                        
## [318] &quot;Waypoint: Manage Source Code with Git&quot;                                     
## [319] &quot;Waypoint: Manipulate Arrays With pop&quot;                                      
## [320] &quot;Waypoint: Manipulate Arrays With push&quot;                                     
## [321] &quot;Waypoint: Manipulate Arrays With shift&quot;                                    
## [322] &quot;Waypoint: Manipulate Arrays With unshift&quot;                                  
## [323] &quot;Waypoint: Manipulate JavaScript Objects&quot;                                   
## [324] &quot;Waypoint: Meet Other Campers in your City&quot;                                 
## [325] &quot;Waypoint: Mobile Responsive Images&quot;                                        
## [326] &quot;Waypoint: Modify Array Data With Indexes&quot;                                  
## [327] &quot;Waypoint: Multiply Two Decimals with JavaScript&quot;                           
## [328] &quot;Waypoint: Multiply Two Numbers with JavaScript&quot;                            
## [329] &quot;Waypoint: Nest an Anchor Element within a Paragraph&quot;                       
## [330] &quot;Waypoint: Nest Many Elements within a Single Div Element&quot;                  
## [331] &quot;Waypoint: Nest one Array within Another Array&quot;                             
## [332] &quot;Waypoint: Override All Other Styles by using Important&quot;                    
## [333] &quot;Waypoint: Override Class Declarations by Styling ID Attributes&quot;            
## [334] &quot;Waypoint: Override Class Declarations with Inline Styles&quot;                  
## [335] &quot;Waypoint: Override Styles in Subsequent CSS&quot;                               
## [336] &quot;Waypoint: Override Styles with Important&quot;                                  
## [337] &quot;Waypoint: Pair Program on Bonfires&quot;                                        
## [338] &quot;Waypoint: Perform Arithmetic Operations on Decimals with JavaScript&quot;       
## [339] &quot;Waypoint: Power Forms with Angular.js&quot;                                     
## [340] &quot;Waypoint: Power Forms with Angularjs&quot;                                      
## [341] &quot;Waypoint: Practice Functional Programming&quot;                                 
## [342] &quot;Waypoint: Prefilter JSON&quot;                                                  
## [343] &quot;Waypoint: Preview our Challenge Map&quot;                                       
## [344] &quot;Waypoint: Prioritize One Style Over Another&quot;                               
## [345] &quot;Waypoint: Reference our Wiki&quot;                                              
## [346] &quot;Waypoint: Reference your Current Object with This&quot;                         
## [347] &quot;Waypoint: Remove an Element Using jQuery&quot;                                  
## [348] &quot;Waypoint: Remove Classes from an element with jQuery&quot;                      
## [349] &quot;Waypoint: Render Images from Data Sources&quot;                                 
## [350] &quot;Waypoint: Responsively Style a Radio Buttons&quot;                              
## [351] &quot;Waypoint: Responsively Style Checkboxes&quot;                                   
## [352] &quot;Waypoint: Responsively Style Radio Buttons&quot;                                
## [353] &quot;Waypoint: Reuse Code with Decorators&quot;                                      
## [354] &quot;Waypoint: Reverse Arrays with reverse&quot;                                     
## [355] &quot;Waypoint: Save your Code Revisions Forever with Git&quot;                       
## [356] &quot;Waypoint: Say Hello to HTML Elements&quot;                                      
## [357] &quot;Waypoint: Scope Your Variables&quot;                                            
## [358] &quot;Waypoint: Set the Font Family of an Element&quot;                               
## [359] &quot;Waypoint: Set the ID of an Element&quot;                                        
## [360] &quot;Waypoint: Sift through Text with Regular Expressions&quot;                      
## [361] &quot;Waypoint: Size your Images&quot;                                                
## [362] &quot;Waypoint: Sort Arrays with sort&quot;                                           
## [363] &quot;Waypoint: Specify How Fonts Should Degrade&quot;                                
## [364] &quot;Waypoint: Split Strings with split&quot;                                        
## [365] &quot;Waypoint: Split your Bootstrap Row&quot;                                        
## [366] &quot;Waypoint: Start a Node.js Server&quot;                                          
## [367] &quot;Waypoint: Start a Nodejs Server&quot;                                           
## [368] &quot;Waypoint: Store Data in MongoDB&quot;                                           
## [369] &quot;Waypoint: Store Multiple Values in one Variable using JavaScript Arrays&quot;   
## [370] &quot;Waypoint: Style Multiple Elements with a CSS Class&quot;                        
## [371] &quot;Waypoint: Style Multiple Elements with a CSS Classes&quot;                      
## [372] &quot;Waypoint: Style Text Inputs as Form Controls&quot;                              
## [373] &quot;Waypoint: Style the HTML Body Element&quot;                                     
## [374] &quot;Waypoint: Subclass one Object to Another&quot;                                  
## [375] &quot;Waypoint: Subtract One Number from Another with JavaScript&quot;                
## [376] &quot;Waypoint: Target a Specific Child of an Element Using jQuery&quot;              
## [377] &quot;Waypoint: Target Elements by Class Using jQuery&quot;                           
## [378] &quot;Waypoint: Target Elements by ID Using jQuery&quot;                              
## [379] &quot;Waypoint: Target Even Numbered Elements Using jQuery&quot;                      
## [380] &quot;Waypoint: Target HTML Elements with Selectors Using jQuery&quot;                
## [381] &quot;Waypoint: Target the Children of an Element Using jQuery&quot;                  
## [382] &quot;Waypoint: Target the Parent of an Element Using jQuery&quot;                    
## [383] &quot;Waypoint: Target the same element with multiple jQuery Selectors&quot;          
## [384] &quot;Waypoint: Taste the Bootstrap Button Color Rainbow&quot;                        
## [385] &quot;Waypoint: Traverse the Prototype Chain&quot;                                    
## [386] &quot;Waypoint: Trigger Click Events with jQuery&quot;                                
## [387] &quot;Waypoint: Trigger jQuery Effects&quot;                                          
## [388] &quot;Waypoint: Trigger on click Events with jQuery&quot;                             
## [389] &quot;Waypoint: Try Camper News&quot;                                                 
## [390] &quot;Waypoint: Turn an Image into a Link&quot;                                       
## [391] &quot;Waypoint: Uncomment HTML&quot;                                                  
## [392] &quot;Waypoint: Understand Boolean Values&quot;                                       
## [393] &quot;Waypoint: Understand Pseudoclassical Patterns&quot;                             
## [394] &quot;Waypoint: Understanding Public and Private Properties&quot;                     
## [395] &quot;Waypoint: Update the Properties of a JavaScript Object&quot;                    
## [396] &quot;Waypoint: Use a CSS Class to Style an Element&quot;                             
## [397] &quot;Waypoint: Use Abbreviated Hex Code&quot;                                        
## [398] &quot;Waypoint: Use an ID Attribute to Style an Element&quot;                         
## [399] &quot;Waypoint: Use appendTo to Move Elements with jQuery&quot;                       
## [400] &quot;Waypoint: Use Bracket Notation to Find the First Character in a String&quot;    
## [401] &quot;Waypoint: Use Bracket Notation to Find the Last Character in a String&quot;     
## [402] &quot;Waypoint: Use Bracket Notation to Find the Nth Character in a String&quot;      
## [403] &quot;Waypoint: Use Bracket Notation to Find the NthtoLast Character in a String&quot;
## [404] &quot;Waypoint: Use Clockwise Notation to Specify the Margin of an Element&quot;      
## [405] &quot;Waypoint: Use Clockwise Notation to Specify the Padding of an Element&quot;     
## [406] &quot;Waypoint: Use Comments to Clarify Code&quot;                                    
## [407] &quot;Waypoint: Use Conditional Logic with If and Else Statements&quot;               
## [408] &quot;Waypoint: Use Conditional Logic with IfElse Statements&quot;                    
## [409] &quot;Waypoint: Use CSS Selectors to Style Elements&quot;                             
## [410] &quot;Waypoint: Use Hex Code for Specific Colors&quot;                                
## [411] &quot;Waypoint: Use Hex Code for Specific Shades of Gray&quot;                        
## [412] &quot;Waypoint: Use Hex Code to Color Elements Blue&quot;                             
## [413] &quot;Waypoint: Use Hex Code to Color Elements Gray&quot;                             
## [414] &quot;Waypoint: Use Hex Code to Color Elements Green&quot;                            
## [415] &quot;Waypoint: Use Hex Code to Color Elements Red&quot;                              
## [416] &quot;Waypoint: Use Hex Code to Color Elements White&quot;                            
## [417] &quot;Waypoint: Use Hex Code to Mix Colors&quot;                                      
## [418] &quot;Waypoint: Use HTML5 to Require a Field&quot;                                    
## [419] &quot;Waypoint: Use jQuery to Modify the Entire Page&quot;                            
## [420] &quot;Waypoint: Use Pseudoclassical Subclasses&quot;                                  
## [421] &quot;Waypoint: Use Responsive Design with Bootstrap Fluid Containers&quot;           
## [422] &quot;Waypoint: Use RGB to Color Elements Blue&quot;                                  
## [423] &quot;Waypoint: Use RGB to Color Elements Gray&quot;                                  
## [424] &quot;Waypoint: Use RGB to Color Elements Green&quot;                                 
## [425] &quot;Waypoint: Use RGB to Color Elements Red&quot;                                   
## [426] &quot;Waypoint: Use RGB to Color Elements White&quot;                                 
## [427] &quot;Waypoint: Use RGB to Mix Colors&quot;                                           
## [428] &quot;Waypoint: Use RGB values to Color Elements&quot;                                
## [429] &quot;Waypoint: Use Spans for Inline Elements&quot;                                   
## [430] &quot;Waypoint: Use the Bootstrap Grid to Put Elements Side By Side&quot;             
## [431] &quot;Waypoint: Use the Javascript Console&quot;                                      
## [432] &quot;Waypoint: Using concat&quot;                                                    
## [433] &quot;Waypoint: Using filter&quot;                                                    
## [434] &quot;Waypoint: Using join&quot;                                                      
## [435] &quot;Waypoint: Using map&quot;                                                       
## [436] &quot;Waypoint: Using reduce&quot;                                                    
## [437] &quot;Waypoint: Using reverse&quot;                                                   
## [438] &quot;Waypoint: Using sort&quot;                                                      
## [439] &quot;Waypoint: Using split&quot;                                                     
## [440] &quot;Waypoint: Using typeof&quot;                                                    
## [441] &quot;Waypoint: Visually Separate Elements with Line Breaks&quot;                     
## [442] &quot;Waypoint: Warn your Users of a Dangerous Action&quot;                           
## [443] &quot;Waypoint: Wrap an Anchor Element within a Paragraph&quot;                       
## [444] &quot;Waypoint: Wrap Many Elements within a Div Element&quot;                         
## [445] &quot;Waypoint: Wrap Many Elements within a Single Div Element&quot;                  
## [446] &quot;Waypoint: Write Functions with jQuery&quot;                                     
## [447] &quot;Waypoint: Write Reusable JavaScript with Functions&quot;                        
## [448] &quot;Where art thou&quot;                                                            
## [449] &quot;Where do I belong&quot;                                                         
## [450] &quot;Write Functions with jQuery&quot;                                               
## [451] &quot;Zipline: Build a JavaScript Calculator&quot;                                    
## [452] &quot;Zipline: Build a Personal Portfolio Webpage&quot;                               
## [453] &quot;Zipline: Build a Pomodoro Clock&quot;                                           
## [454] &quot;Zipline: Build a Random Quote Machine&quot;                                     
## [455] &quot;Zipline: Build a Simon Game&quot;                                               
## [456] &quot;Zipline: Build a Tic Tac Toe Game&quot;                                         
## [457] &quot;Zipline: Build a Wikipedia Viewer&quot;                                         
## [458] &quot;Zipline: Show the Local Weather&quot;                                           
## [459] &quot;Zipline: Stylize Stories on Camper News&quot;                                   
## [460] &quot;Zipline: Use the Twitch.tv JSON API&quot;                                       
## [461] &quot;Zipline: Use the Twitchtv JSON API&quot;                                        
## [462] &quot;Zipline: Wikipedia Viewer&quot;</code></pre>
<p>Wow! So 462 challenges. A quick skim of the levels indicate that these data are pretty clean but it’s hard to tell if there are duplicates. There are definitely some NA values, and some labelled as ““. I’m going to remove those from this dataset.</p>
<pre class="r"><code>fcc_df3 &lt;- fcc_df2 %&gt;% filter(!is.na(name)) %&gt;% filter(!name == 
    &quot;&quot;) %&gt;% droplevels()

# Validate that there are no more NA course names
sum(is.na(fcc_df3$name))</code></pre>
<pre><code>## [1] 0</code></pre>
<p>I’ll deal more with the course names a bit later. One more thing before moving on; I’d like to separate the “name” column into “type” and course, splitting the course name at the “:”</p>
<pre class="r"><code># Subset data frame to only include student entries where the
# course name has a &#39;:&#39; and separate course name into 2
# columns: type and course
fcc_sub1 &lt;- fcc_df3 %&gt;% filter(grepl(&quot;\\:\\s&quot;, name)) %&gt;% separate(col = name, 
    into = c(&quot;type&quot;, &quot;course&quot;), sep = &quot;: &quot;)

# Subset data frame to only include student entries where
# course name does not have a &#39;:&#39;. Add a new &#39;type&#39; column
# filled with NA
fcc_sub2 &lt;- fcc_df3 %&gt;% filter(!grepl(&quot;\\:\\s&quot;, name)) %&gt;% mutate(type = NA)

# Rename the &#39;name&#39; variable in the second subset to &#39;course&#39;
# (to match first subset)
fcc_sub2 &lt;- rename(fcc_sub2, course = name)

# Bind subsets together
fcc_all &lt;- rbind(fcc_sub1, fcc_sub2)

# Make both &#39;course&#39; and &#39;type&#39; factors
fcc_all$course &lt;- as.factor(fcc_all$course)
fcc_all$type &lt;- as.factor(fcc_all$type)

# Check structure of &#39;course&#39;
str(fcc_all$course)</code></pre>
<pre><code>##  Factor w/ 370 levels &quot;Access Array Data with Indexes&quot;,..: 187 187 238 31 110 306 214 150 255 163 ...</code></pre>
<p>Perfect! That will make dealing with course names easier in the future, and it looks like it trimmed us down to 370 courses (some of them must have had duplicate names).</p>
<p>While we’re at it, let’s clean up our completedDate variable; it should be a POSIXct object.</p>
<pre class="r"><code># Convert characters to numeric
fcc_all$completedDate &lt;- as.numeric(fcc_all$completedDate)

# Divide by 1000 to account for the numbers being in
# milliseconds
fcc_all$completedDate &lt;- fcc_all[, &quot;completedDate&quot;]/1000

# Convert to POSIXct object
fcc_all$completedDate &lt;- as.POSIXct((fcc_all$completedDate), 
    origin = &quot;1970-01-01&quot;, tz = &quot;GMT&quot;)</code></pre>
<p>Perfect. Were all the dates coded correctly?</p>
<p>Let’s see if any entries are recorded as being completed before FCC launched in October 2014.</p>
<pre class="r"><code>wrong_dates &lt;- fcc_all %&gt;% 
			filter(completedDate &lt; &quot;2014-10-01&quot;)</code></pre>
<p>Oops! 19 of our entries have incorrectly coded dates. We’ll remove those from the dataset.</p>
<pre class="r"><code>fcc_all &lt;- fcc_all %&gt;% 
	       filter(completedDate &gt; &quot;2014-10-01&quot;)</code></pre>
<p>Do we have any NA values in our completedDate column? If so, we’ll remove those as well.</p>
<pre class="r"><code># Count NA
sum(is.na(fcc_all$completedDate))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code># Remove NA
fcc_all &lt;- fcc_all %&gt;% 
	       filter(!is.na(completedDate))</code></pre>
<p>Ok, so far so good. Let’s take another quick look at our structure.</p>
<pre class="r"><code>str(fcc_all)</code></pre>
<pre><code>## &#39;data.frame&#39;:    7216723 obs. of  5 variables:
##  $ .id          : Factor w/ 102882 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ type         : Factor w/ 6 levels &quot;&quot;,&quot;Basejump&quot;,..: 5 5 5 5 5 5 5 5 5 5 ...
##  $ course       : Factor w/ 370 levels &quot;Access Array Data with Indexes&quot;,..: 187 187 238 31 110 306 214 150 255 163 ...
##  $ completedDate: POSIXct, format: &quot;2015-06-18 18:02:46&quot; &quot;2015-06-18 18:03:02&quot; ...
##  $ solution     : chr  NA NA NA NA ...</code></pre>
<p>That looks much better!</p>
</div>
</div>
<div id="feature-engineering" class="section level2">
<h2>Feature Engineering</h2>
<div id="using-original-dataset" class="section level3">
<h3>Using Original Dataset</h3>
<p>There are a few things that I’m interested in that aren’t readily available from this dataset.</p>
<ul>
<li>What order did each student complete the courses in?</li>
<li>How long did it take for each student to finish one course and then complete another?</li>
<li>Which class did each student take <em>before</em> the current course and which did they take <em>after</em>?</li>
<li>Did students generally take FCC classes in the order that they are offered?</li>
<li>Are the most frequently completed courses the ones offered at the beginning?</li>
</ul>
<p>We’ll look at one student first:</p>
<p><em>I chose the second student because that student only completed 25 courses, a much more reasonable starting-point than the 226 completed by student #1</em></p>
<pre class="r"><code>second_student &lt;- fcc_all %&gt;% 
			     filter(.id == &quot;2&quot;)

second_student</code></pre>
<pre><code>##    .id type                             course       completedDate
## 1    2 &lt;NA&gt;     Learn how Free Code Camp Works 2015-05-21 17:44:57
## 2    2 &lt;NA&gt;                 Join Our Chat Room 2015-05-21 17:58:10
## 3    2 &lt;NA&gt;          Preview our Challenge Map 2015-05-21 18:45:44
## 4    2 &lt;NA&gt;             Browse our Field Guide 2015-05-21 18:49:15
## 5    2 &lt;NA&gt;      Customize your Portfolio Page 2015-05-21 19:06:19
## 6    2 &lt;NA&gt;                    Try Camper News 2015-05-21 19:22:35
## 7    2 &lt;NA&gt;    Meet Other Campers in your City 2015-05-21 19:45:10
## 8    2 &lt;NA&gt;  Get Help the Hacker Way with RSAP 2015-05-21 19:46:43
## 9    2 &lt;NA&gt;     Build a Landing Page with HTML 2015-05-22 14:40:57
## 10   2 &lt;NA&gt;                Style Text with CSS 2015-05-22 14:41:30
## 11   2 &lt;NA&gt;                 Space Out with CSS 2015-05-22 14:47:10
## 12   2 &lt;NA&gt;          Design a Layout with HTML 2015-05-22 14:49:57
## 13   2 &lt;NA&gt; Design Responsively with Bootstrap 2015-05-22 14:56:51
## 14   2 &lt;NA&gt;            Get Started with jQuery 2015-05-22 14:57:21
## 15   2 &lt;NA&gt;        Write Functions with jQuery 2015-05-22 15:10:05
## 16   2 &lt;NA&gt;               Harness Dynamic HTML 2015-05-22 15:31:01
## 17   2 &lt;NA&gt;           Listen for jQuery Events 2015-05-22 15:31:32
## 18   2 &lt;NA&gt;             Trigger jQuery Effects 2015-05-22 16:02:40
## 19   2 &lt;NA&gt;       Learn Basic Computer Science 2015-05-22 17:37:14
## 20   2 &lt;NA&gt;                        Learn Loops 2015-05-22 17:37:28
## 21   2 &lt;NA&gt;            Learn Computer Hardware 2015-05-24 22:20:35
## 22   2 &lt;NA&gt;          Learn Computer Networking 2015-05-25 22:03:14
## 23   2 &lt;NA&gt;                Learn Boolean Logic 2015-05-26 01:48:40
## 24   2 &lt;NA&gt;            Learn Computer Security 2015-05-26 02:07:25
## 25   2 &lt;NA&gt;                       Meet Bonfire 2015-05-22 00:15:04
##                                                                                                                                                                                                    solution
## 1                                                                                                                                                                                                      &lt;NA&gt;
## 2                                                                                                                                                                                                      &lt;NA&gt;
## 3                                                                                                                                                                                                      &lt;NA&gt;
## 4                                                                                                                                                                                                      &lt;NA&gt;
## 5                                                                                                                                                                                                      &lt;NA&gt;
## 6                                                                                                                                                                                                      &lt;NA&gt;
## 7                                                                                                                                                                                                      &lt;NA&gt;
## 8                                                                                                                                                                                                      &lt;NA&gt;
## 9                                                                                                                                                                                                      &lt;NA&gt;
## 10                                                                                                                                                                                                     &lt;NA&gt;
## 11                                                                                                                                                                                                     &lt;NA&gt;
## 12                                                                                                                                                                                                     &lt;NA&gt;
## 13                                                                                                                                                                                                     &lt;NA&gt;
## 14                                                                                                                                                                                                     &lt;NA&gt;
## 15                                                                                                                                                                                                     &lt;NA&gt;
## 16                                                                                                                                                                                                     &lt;NA&gt;
## 17                                                                                                                                                                                                     &lt;NA&gt;
## 18                                                                                                                                                                                                     &lt;NA&gt;
## 19                                                                                                                                                                                                     &lt;NA&gt;
## 20                                                                                                                                                                                                     &lt;NA&gt;
## 21                                                                                                                                                                                                     &lt;NA&gt;
## 22                                                                                                                                                                                                     &lt;NA&gt;
## 23                                                                                                                                                                                                     &lt;NA&gt;
## 24                                                                                                                                                                                                     &lt;NA&gt;
## 25 function meetBonfire(argument) {\n  // Good luck!\n  console.log(&quot;you can read this function&#39;s argument in the developer tools&quot;, argument);\n\n  return true;\n}\n\n\n\nmeetBonfire(&quot;You can do this!&quot;);</code></pre>
<p>So the second student in our list completed 25 courses. I’m going to try extracting the information I want on this sub-sample first to ensure that it’s behaving the way I’d expect before using it to generate information for 102,000 students.</p>
<pre class="r"><code>second_student_2 &lt;- second_student %&gt;% 
		group_by(.id) %&gt;% 
		arrange(completedDate) %&gt;% 
    		mutate(st_cour_num = rank(completedDate), 
			    time_since_last = completedDate - lag(completedDate), 
			    from_type = lag(type), 
			    from_course = lag(course), 
        			    to_type = lead(type), 
			    to_course = lead(course))

head(second_student_2)</code></pre>
<pre><code>## Source: local data frame [6 x 11]
## Groups: .id [1]
## 
##      .id   type                         course       completedDate
##   &lt;fctr&gt; &lt;fctr&gt;                         &lt;fctr&gt;              &lt;dttm&gt;
## 1      2     NA Learn how Free Code Camp Works 2015-05-21 17:44:57
## 2      2     NA             Join Our Chat Room 2015-05-21 17:58:10
## 3      2     NA      Preview our Challenge Map 2015-05-21 18:45:44
## 4      2     NA         Browse our Field Guide 2015-05-21 18:49:15
## 5      2     NA  Customize your Portfolio Page 2015-05-21 19:06:19
## 6      2     NA                Try Camper News 2015-05-21 19:22:35
## # ... with 7 more variables: solution &lt;chr&gt;, st_cour_num &lt;dbl&gt;,
## #   time_since_last &lt;time&gt;, from_type &lt;fctr&gt;, from_course &lt;fctr&gt;,
## #   to_type &lt;fctr&gt;, to_course &lt;fctr&gt;</code></pre>
<p>Great! That works just as we’d expect. Let’s make sure it doesn’t do anything strange when there are more than one student.</p>
<pre class="r"><code>second_third &lt;- fcc_all %&gt;% 
			 filter(.id %in% c(&quot;2&quot;, &quot;3&quot;)) %&gt;% 
    			 group_by(.id) %&gt;% 
			 arrange(completedDate) %&gt;% 
			 mutate(st_cour_num = rank(completedDate, ties.method = &quot;first&quot;), 
			 	     time_since_last = completedDate - lag(completedDate), 
				     from_type = lag(type), 
				     from_course = lag(course), 
				     to_type = lead(type), 
				     to_course = lead(course))

second_third &lt;- second_third %&gt;% 
			 arrange(.id, st_cour_num)</code></pre>
<p>So far so good. Let’s check rows 25 - 27 to make sure our counts started over again with a new student.</p>
<pre class="r"><code>second_third[25:27, c(&quot;.id&quot;, &quot;st_cour_num&quot;)]</code></pre>
<pre><code>## Source: local data frame [3 x 2]
## Groups: .id [2]
## 
##      .id st_cour_num
##   &lt;fctr&gt;       &lt;int&gt;
## 1      2          25
## 2      3           1
## 3      3           2</code></pre>
<p>Perfect! We will apply this to the entire data structure, but I want to modify a few more things first.</p>
</div>
<div id="web-scraping-new-data" class="section level3">
<h3>Web Scraping New Data</h3>
<p>I wonder if the most commonly taken courses are the ones offered at the beginning of the Free Code Camp program. To find out, I’m going to scrape the information from an archived version of the FCC course map from January 2016 (approximately 2 weeks after this dataset was released). I’ll use the <code>rvest</code> package for this.</p>
<pre class="r"><code>url &lt;- &quot;https://web.archive.org/web/20160101182240/http://www.freecodecamp.com/map#getting-started&quot;
webpage &lt;- read_html(curl(url, handle = curl::new_handle(useragent = &quot;Chrome&quot;)))

course_table &lt;- html_nodes(webpage, &quot;.col-md-offset-2 &gt; .row .col-md-9&quot;)
course_table2 &lt;- html_text(course_table)
course_table2 &lt;- as.data.frame(course_table2)</code></pre>
<p>Now we have a list of the courses in the order that FCC has them on their map. I’m going to add a few columns to this:</p>
<ul>
<li>What section of the FCC course map did this course come from?</li>
<li>What number course is this inside each section and inside the entire map?</li>
</ul>
<pre class="r"><code>course_table3 &lt;- course_table2 %&gt;% 
	mutate(section = ifelse(row_number() %in% 1:5, &quot;Getting Started&quot;, 
ifelse(row_number() %in% 6:73, &quot;HTML5 and CSS&quot;, 
    ifelse(row_number() %in% 74:104, &quot;Responsive Design with Bootstrap&quot;, 
        ifelse(row_number() %in% 105:108, &quot;Gear up for Success&quot;, 
            ifelse(row_number() %in% 109:126, &quot;jQuery&quot;, ifelse(row_number() %in% 127:230, &quot;Basic JavaScript&quot;, 
            ifelse(row_number() %in% 231:243, &quot;Object Oriented and Functional Programming&quot;, 
                ifelse(row_number() %in% 244:260, &quot;Basic Algorithm Scripting&quot;, 
                  ifelse(row_number() %in% 261:265, &quot;Basic Front End Development Projects&quot;, 
                    ifelse(row_number() %in% 266:286, &quot;Intermediate Algorithm Scripting&quot;, 
                      ifelse(row_number() %in% 287:293, &quot;JSON APIs and Ajax&quot;, 
                        ifelse(row_number() %in% 294:299, &quot;Intermediate Front End Development Projects&quot;, 
                          ifelse(row_number() == 300, &quot;Claim Your Front End Development Certificate&quot;, 
                            ifelse(row_number() == 301, &quot;Sass&quot;, 
                              ifelse(row_number() == 302, &quot;React&quot;, 
                                ifelse(row_number() %in% 303:307, &quot;React Projects&quot;, 
                                ifelse(row_number() == 308, &quot;D3&quot;, 
                                 ifelse(row_number() %in% 309:313, &quot;Data Visualization Projects&quot;, 
                                    ifelse(row_number() == 314, &quot;Claim Your Data Visualization Certificate&quot;, 
                                      ifelse(row_number() %in% 315:317, &quot;Upper Intermediate Algorithm Scripting&quot;, 
                                        ifelse(row_number() %in% 318:319, &quot;Automated Testing and Debugging&quot;, 
                                          ifelse(row_number() %in%  320:325, &quot;Advanced Algorithm Scripting&quot;, 
                                            ifelse(row_number() %in% 326:330, &quot;Node.js and Express.js&quot;, 
                                              ifelse(row_number() ==  331, &quot;Git&quot;, 
                                              ifelse(row_number() == 332, &quot;MongoDB&quot;,  
                                              ifelse(row_number() %in% 333:338, &quot;API Projects&quot;, 
                                                  ifelse(row_number() %in%  339:343,  &quot;Dynamic Web Applications&quot;, 
                                                    ifelse(row_number() ==  344, &quot;Claim Your Back End Development Certificate&quot;, 
                                                      NA))))))))))))))))))))))))))))) %&gt;% 
    group_by(section) %&gt;% mutate(coursenum = row_number()) %&gt;% 
    ungroup %&gt;% mutate(overallnum = row_number())</code></pre>
<p>I do plan to join this data table with the student data that we already have, but currently, the names won’t match. Let’s clean it up a bit.</p>
<pre class="r"><code># Rename column
course_table3 &lt;- rename(course_table3, course = course_table2)

# Remove everything after (and including) the phrase &quot;incomplete&quot; from course column
course_table3$course &lt;- gsub(&quot;(.*?)Incomplete.*&quot;, &quot;\\1&quot;, course_table3$course)

# Separate the course column into Type and Course columns. 
course_table3 &lt;- separate(course_table3, col = course, into = c(&quot;type&quot;, &quot;course&quot;), sep = &quot;: &quot;)

# Capitalize the first letter of type column
course_table3$type &lt;- capitalize(course_table3$type) 

# Remove trailing space from course column
course_table3$course &lt;- gsub(&quot;\\s$&quot;, &quot;&quot;, course_table3$course)

# Recode words that are entered differently in the original dataset
course_table4 &lt;- course_table3 %&gt;% 
                  mutate(course = gsub(&quot;(.*?)\\.(.*?)&quot;, &quot;\\1\\2&quot;, course),       # Removing the &quot;.&quot; at beginning of words
                         course = gsub(&quot;(.*?)\\(\\).*&quot;, &quot;\\1&quot;, course),          # Removing () at the end of pop(), shift() etc.
                         course = gsub(&quot;Nth\\-to\\-Last&quot;, &quot;NthtoLast&quot;, course),  # Removing hyphens     
                         course = gsub(&quot;Geo-location&quot;, &quot;Geolocation&quot;, course),   # Remove hyphen from Geo-location
                         course = gsub(&quot;Node(\\s)js|Nodejs&quot;, &quot;Node\\.js&quot;, course),
                         course = gsub(&quot;Expressjs|Express js&quot;, &quot;Express\\.js&quot;, course))       

# Remove trailing space from course column
course_table4$course &lt;- gsub(&quot;\\s$&quot;, &quot;&quot;, course_table4$course)</code></pre>
<p>Ok, any other non-matches come from errors in our original dataset or courses whose name was different (or that no longer existed) when this dataset was published.</p>
<p>Here are a few quick fixes to the original dataset.</p>
<pre class="r"><code>fcc_all2 &lt;- fcc_all %&gt;% 
		mutate(course = recode(course, `Add Font Awesome Icons all of our Buttons` = &quot;Add Font Awesome Icons to all of our Buttons&quot;), 
    course = gsub(&quot;Pintrest&quot;, &quot;Pinterest&quot;, course), course = gsub(&quot;Node(\\s)js|Nodejs&quot;, 
        &quot;Node\\.js&quot;, course), course = gsub(&quot;Build Web Apps with Expressjs|Build Web Apps with Express\\.js|Build Web Apps with Express js&quot;, 
        &quot;Build Web Apps with Express\\.js&quot;, course), course = recode(course, 
        `Add Free Code Camp to your LinkedIn Profile` = &quot;Join our LinkedIn Alumni Network&quot;), 
    course = recode(course, `Add Different a Margin to Each Side of an Element` = &quot;Add Different Margins to Each Side of an Element&quot;), 
    course = recode(course, `Check the Length Property of a String Variable` = &quot;Find the Length of a String&quot;), 
    course = gsub(&quot;\\.concat&quot;, &quot;concat&quot;, course), course = gsub(&quot;White Space&quot;, 
        &quot;Whitespace&quot;, course), course = recode(course, `Learn JavaScript For Loops` = &quot;Iterate with JavaScript For Loops&quot;), 
    course = recode(course, `Learn JavaScript While Loops` = &quot;Iterate with JavaScript While Loops&quot;), 
    course = recode(course, `Mobile Responsive Images` = &quot;Make Images Mobile Responsive&quot;), 
    course = recode(course, `Override Styles with Important` = &quot;Override All Other Styles by using Important&quot;), 
    course = recode(course, `Style Multiple Elements with a CSS Classes` = &quot;Style Multiple Elements with a CSS Class&quot;), 
    course = recode(course, `Trigger jQuery Effects` = &quot;Trigger Click Events with jQuery&quot;), 
    course = recode(course, `Trigger on click Events with jQuery` = &quot;Trigger Click Events with jQuery&quot;), 
    course = recode(course, `Try Camper News` = &quot;Browse Camper News&quot;), 
    course = recode(course, `Update the Properties of a JavaScript Object` = &quot;Updating Object Properties&quot;), 
    course = recode(course, `Use Conditional Logic with If and Else Statements` = &quot;Use Conditional Logic with If Statements&quot;), 
    course = recode(course, `Use Conditional Logic with IfElse Statements` = &quot;Use Conditional Logic with If Statements&quot;), 
    course = gsub(&quot;twitch\\.tv&quot;, &quot;twitchtv&quot;, course), course = recode(course, 
        `Wikipedia Viewer` = &quot;Build a Wikipedia Viewer&quot;), course = recode(course, 
        `Wrap an Anchor Element within a Paragraph` = &quot;Nest an Anchor Element within a Paragraph&quot;), 
    course = recode(course, `Wrap Many Elements within a Div Element` = &quot;Nest Many Elements within a Single Div Element&quot;), 
    course = recode(course, `Wrap Many Elements within a Single Div Element` = &quot;Nest Many Elements within a Single Div Element&quot;))

# Remove trailing space from course column
fcc_all2$course &lt;- gsub(&quot;\\s$&quot;, &quot;&quot;, fcc_all2$course)</code></pre>
<p>Now to join the two dataframes based on the “course” column.</p>
<pre class="r"><code>sc_full &lt;- left_join(fcc_all2, course_table4, by = &quot;course&quot;)</code></pre>
<p>How many of our entries are still missing a “section” label?</p>
<pre class="r"><code>sum(is.na(sc_full$section))</code></pre>
<pre><code>## [1] 539128</code></pre>
<p>That’s 539,128 entries (or about 7.5% of our entire dataset). I checked the following subset of data (only focused on entries with an “NA” in <code>section</code>), and then returned to code above to adjust the names of courses as necessary. Any remaining unmatched courses at this point were not on the FCC course map at the end of 2015, and thus will be removed from this dataset.</p>
<pre class="r"><code># Filter only entries with NA sections
sub_na &lt;- sc_full %&gt;% filter(is.na(section)) %&gt;% group_by(course) %&gt;% 
    summarise(count = n())

# Remove anything that still has missing section values
sc_full2 &lt;- sc_full %&gt;% filter(!is.na(section))

# Remove the original dataset&#39;s &#39;Type&#39; column in exchange for
# the amended &#39;Type column&#39;
sc_full3 &lt;- sc_full2 %&gt;% select(-2)

sc_full3 &lt;- rename(sc_full3, type = type.y)</code></pre>
</div>
<div id="engineered-variables" class="section level3">
<h3>Engineered Variables</h3>
<p>Perfect! Now our data frame is all set to add other variables.</p>
<pre class="r"><code>sc_full4 &lt;- sc_full3 %&gt;% group_by(.id) %&gt;% arrange(completedDate) %&gt;% 
    mutate(st_cour_num = rank(completedDate, ties.method = &quot;first&quot;), 
        time_since_last = completedDate - lag(completedDate), 
        from_type = lag(type), from_course = lag(course), from_section = lag(section), 
        to_type = lead(type), to_course = lead(course), to_section = lead(section)) %&gt;% 
    ungroup()</code></pre>
<p>Let’s look at the top few data entries.</p>
<pre class="r"><code>head(sc_full4)</code></pre>
<pre><code>## # A tibble: 6 × 17
##      .id       course       completedDate
##   &lt;fctr&gt;        &lt;chr&gt;              &lt;dttm&gt;
## 1    954 Meet Bonfire 2015-01-28 06:41:03
## 2    954 Meet Bonfire 2015-01-28 06:41:03
## 3    954 Meet Bonfire 2015-01-28 06:41:03
## 4    954 Meet Bonfire 2015-01-28 06:41:03
## 5    954 Meet Bonfire 2015-01-28 06:41:03
## 6    954 Meet Bonfire 2015-01-28 06:41:03
## # ... with 14 more variables: solution &lt;chr&gt;, X &lt;int&gt;, type &lt;chr&gt;,
## #   section &lt;chr&gt;, coursenum &lt;int&gt;, overallnum &lt;int&gt;, st_cour_num &lt;int&gt;,
## #   time_since_last &lt;time&gt;, from_type &lt;chr&gt;, from_course &lt;chr&gt;,
## #   from_section &lt;chr&gt;, to_type &lt;chr&gt;, to_course &lt;chr&gt;, to_section &lt;chr&gt;</code></pre>
<p>Great! Now that I have the following variables to work with:</p>
<ul>
<li><strong>.id</strong> : Individual student ID number (generated from JSON)</li>
<li><strong>course</strong> : Course name (cleaned to match course map from Jan 2016)</li>
<li><strong>completedDate</strong> : The POSIXct date and time that a course was completed by a student</li>
<li><strong>solution</strong> : The student’s solution to a given problem</li>
<li><strong>type</strong> : The type of course (Basejump, Bonfire, Waypoint, Zipline)</li>
<li><strong>section</strong> :The specific section that each course falls into on the course map (“Getting Started”, “HTML5 and CSS”, etc.)</li>
<li><strong>coursenum</strong> : The number of the course within each section</li>
<li><strong>overallnum</strong> :The number of the course within the entire curriculum</li>
<li><strong>st_cour_num</strong> : The number of the course within each student’s specific journey (i.e., a student’s first completed class would be 1, 2nd completed class would be 2, etc.)</li>
<li><strong>time_since_last</strong> : The time between the completion of the current course and the completion of the last course (in seconds)</li>
<li><strong>from_type</strong> : The type of class that was taken immediately before the present class (Basejump, Bonfire, Waypoint, Zipline)</li>
<li><strong>from_course</strong> : The name of the class that was taken immediately before the present class</li>
<li><strong>from_section</strong> : The section of the course curriculum that the last class taken was in</li>
<li><strong>to_type</strong> : The type of class that was taken immediately after the present class (Basejump, Bonfire, Waypoint, Zipline)</li>
<li><strong>to_course</strong> : The name of the class that was taken immediately after the present class</li>
<li><strong>to_section</strong> : The section of the course curriculum that the next class is in</li>
</ul>
</div>
</div>
<div id="data-visualizations" class="section level2">
<h2>Data Visualizations</h2>
<p>Now that I have my variables sorted and my data cleaned, let’s try to answer a few simple questions.</p>
<div id="what-class-do-fcc-students-start-with" class="section level3">
<h3>What class do FCC students start with?</h3>
<ul>
<li>Does every student start with the same class?</li>
</ul>
<pre class="r"><code># Separate out first courses
first &lt;- sc_full4 %&gt;% 
	   filter(st_cour_num == 1) %&gt;% 
	   droplevels()

# How many different courses were the first ones taken?
length(unique(sc_full4))</code></pre>
<pre><code>## [1] 17</code></pre>
<p>It looks like most users start in the same place. Let’s see how the popularity of first courses breaks down.</p>
<pre class="r"><code># Count number of students for each course first
first_2 &lt;- first %&gt;% group_by(course) %&gt;% summarise(n = n()) %&gt;% 
    ungroup() %&gt;% mutate(rank = dense_rank(desc(n))) %&gt;% filter(rank &lt;= 
    10) %&gt;% arrange(rank)

fig1 &lt;- hchart(first_2, &quot;column&quot;, x = course, y = n, zoomType = &quot;x&quot;) %&gt;% 
    hc_xAxis(title = list(text = &quot;First Completed Course on FCC&quot;)) %&gt;% 
    hc_yAxis(title = list(text = &quot;Number of Students&quot;), max = 50000) %&gt;% 
    hc_chart(zoomType = &quot;x&quot;)

fig1</code></pre>
<p><img src="figure1.png" alt="Bar graph showing how many students have taken each course. The course “Learn how FCC works” is the most popular" /><br />
</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>So about 48% of users start with the very first course in the curriculum “Learn How Free Code Camp Works”, another 10% skip straight to the first course in the “HTML5 and CSS” section to start their FCC journey. The remaining 42% of users started their first class on random courses throughout the curriculum.</p>
</div>
<div id="which-classes-are-the-most-popular" class="section level3">
<h3>Which classes are the most popular?</h3>
<ul>
<li>How many students completed each course at some point?
<ul>
<li>Note: This figure is zoom-able!</li>
</ul></li>
</ul>
<pre class="r"><code>pop_fig &lt;- sc_full4 %&gt;% 
		group_by(overallnum, section, course) %&gt;% 
    		summarise(count = n()) %&gt;% 
		arrange(overallnum) %&gt;% ungroup()


# Plot
fig2 &lt;- hchart(pop_fig, &quot;column&quot;, x = course, y = count, color = section) %&gt;% 
    hc_title(text = &quot;Course Completion in Curriculum Order&quot;) %&gt;% 
    hc_xAxis(title = list(text = &quot;Completed Course on FCC (in order of FCC course curriculum)&quot;)) %&gt;% 
    hc_yAxis(title = list(text = &quot;Number of Students&quot;), max = 1e+05) %&gt;% 
    hc_chart(zoomType = &quot;xy&quot;) %&gt;% 
    hc_tooltip(headerFormat = &quot;&quot;, 
    	pointFormat = &quot;&lt;b&gt;Class: {point.course}&lt;/b&gt; &lt;br&gt;
    	Section: {point.section}&lt;br&gt;
    	Number of Students: {point.y}&quot;)

fig2</code></pre>
<p><img src="figure2.png" alt="Bar graph showing how many students have taken in the order that the courses are offered. The first video in each section appears to be most popular and then attendance drops off for subsequent classes" /><br />
</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>It definitely seems like the courses offered earlier in the curriculum are completed more frequently than courses offered later in the curriculum. There is also a spike in course completion at the beginning of the “HTML5 and CSS” and “Responsive Design with Boostrap” sections that declines throughout the course section. In the latter, that drop-off seems to happen sharply after the course “Line up Form Elements Responsively with Bootstrap” where almost 11,000 did not complete the next course.</p>
<p>I wonder how the amount of time spent on courses changes throughout the curriculum, as courses (theoretically) get more difficult.</p>
<p><em>For this figure, I eliminated all course completion times that were over 1,210,000 seconds (14 days).</em></p>
<pre class="r"><code>time_spent &lt;- sc_full4 %&gt;% 
			group_by(overallnum, section, course) %&gt;% 
    			filter(!is.na(time_since_last)) %&gt;% 
			filter(time_since_last &lt; 1210000) %&gt;% 
			mutate(time_since_last_m = time_since_last/60) %&gt;% 
    			summarise(median = median(time_since_last_m), 
					  mean = mean(time_since_last_m), 
        					  sd = sd(time_since_last_m))

fig3 &lt;- hchart(time_spent, &quot;column&quot;, x = course, y = mean, color = section) %&gt;% 
    hc_title(text = &quot;Average Time for Course Completion&quot;) %&gt;% 
    hc_subtitle(text = &quot;&lt;i&gt;Does not contain course completion for students&#39; first class&lt;/i&gt;&quot;) %&gt;% 
    hc_xAxis(title = list(text = &quot;Completed Course on FCC (in order of FCC course curriculum)&quot;)) %&gt;% 
    hc_yAxis(title = list(text = &quot;Mean Time to Course Completion (minutes)&quot;), 
        max = 6800) %&gt;% hc_chart(zoomType = &quot;xy&quot;) %&gt;% hc_tooltip(headerFormat = &quot;&quot;, 
    pointFormat = &quot;&lt;b&gt;Class: {point.course}&lt;/b&gt; &lt;br&gt;Section: {point.section}&lt;br&gt;Mean time to completion: {point.y} minutes&quot;, 
    valueDecimals = 2)

fig3</code></pre>
<p><img src="figure3.png" alt="Bar graph showing the average time for course completion (in minutes) not including their first class." /><br />
</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>The class that took the longest to complete (“Claim Your Backend Development Certificate” with average 6845 minutes or 4.75 days) is the last and one of the least popular courses in the curriculum. It is possible that students completed all of the other courses and returned to FCC days later to claim their certificate.</p>
<p>The next courses that took the longest to complete were:</p>
<ul>
<li>Build a Voting App (6675 minutes or 4.6 days)</li>
<li>Build a Nightlife Coordination App (4861 minutes or 3.4 days)</li>
<li>Use the Twitchtv JSON API (4289 minutes or 3 days)</li>
<li>Build a Simon Game (4280 minutes or 3 days)</li>
</ul>
<p>These courses either came immediately after a break (that was less than two weeks in duration) for many students or took students longer on these courses than others in the curriculum. It may be worth investigating how long each of these projects is projected to take.</p>
</div>
<div id="how-do-students-flow-through-the-courses" class="section level3">
<h3>How do students flow through the courses?</h3>
<p>Originally, I planned to depict student flow through the various FCC courses using a <a href="https://en.wikipedia.org/wiki/Sankey_diagram">Sankey plot</a>, but with so many courses in the curriculum this did not seem like a good option. I decided to visualize student course map as a network using the <code>igraph</code> and <code>highcharter</code> packages. Below, color indicates the section of each course, connections indicate flow of students from one course to another and the thickness of each connection indicates how many students followed that path. The size of each circle indicates how many students have taken each course.</p>
<p><em>Hover over any point for more information and zoom in on sections for clearer detail</em></p>
<pre class="r"><code>nodes &lt;- sc_full4 %&gt;% 
		group_by(course, section, overallnum) %&gt;% 
    		summarise(count = n()) %&gt;% 
		ungroup()

edges &lt;- sc_full4 %&gt;% 
		group_by(from_course, to_course) %&gt;% 
		summarise(weight = n()) %&gt;% 
    		filter(!is.na(to_course), !is.na(from_course)) %&gt;% 
		ungroup() %&gt;% 
    		filter(weight &gt; 200)
        

# Make graph object
net &lt;- graph.data.frame(edges, nodes, directed = FALSE)

V(net)$color &lt;- colorize(V(net)$section)
V(net)$size &lt;- V(net)$count
E(net)$width &lt;- E(net)$weight/4000
V(net)$Course_Number &lt;- nodes$overallnum

# Plot graph using highcharter
set.seed(10)
fig4 &lt;- hchart(net, minSize = 3, maxSize = 20, layout = layout_nicely)

fig4</code></pre>
<p><img src="figure4.png" alt="Network graph showing student flow throughout the FCC courses" /><br />
</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>There are several notable things about this figure:</p>
<ul>
<li>The “Getting Started” section is the “jumping off point” for many different tracks</li>
<li>One of the most frequently used tracks runs through the HTML5 and CSS section</li>
<li>Certain parts of the HTML5 and CSS section (i.e., the parts all about changing colors) are taken in order, while others skip entire chunks of the section (See the heavily followed path from class #8 (Inform with the Paragraph Element) and class #40 (Check radio buttons and checkboxes by default)).</li>
<li>Users tend to flow straight from the jQuery section into Basic JavaScript following classes mostly in the recommended order</li>
<li>Fewer users flow through the Intermediate and Advanced algorithm scripting sections than the Basic algorithm scripting section</li>
<li>Several courses don’t follow any typical flow with the rest of the course curriculum. These courses seem to be treated as “stand-alone” courses instead of integrated parts of the map, but are also infrequently taken in general. These courses are:
<ul>
<li>Courses in the Node.js and Express.js section</li>
<li>“Get Set for Basejumps”</li>
<li>“Save your code revisions forever with Git”</li>
<li>Courses in the Dynamic Web application section</li>
</ul></li>
</ul>
</div>
<div id="how-many-courses-do-students-take" class="section level3">
<h3>How many courses do students take?</h3>
<p>Given that there are 344 courses in the curriculum map that match the courses that these students have taken, how many does each student generally take?</p>
<pre class="r"><code>student_courses &lt;- sc_full4 %&gt;% 
		group_by(.id) %&gt;% 
		mutate(time = as.numeric(time_since_last, units = &quot;mins&quot;)) %&gt;% 
		summarise(count = n(), 
			total_time = sum(time, na.rm = TRUE), 
			median_time = median(time, na.rm = TRUE), 
    			average_time = mean(time, na.rm = TRUE)) %&gt;% 
			mutate(time_per_class = (total_time/count)) %&gt;% 
    			filter(count &gt; 0)

fig5 &lt;- hchart(student_courses$count) %&gt;% 
	hc_title(text = &quot;Number of Courses Completed&quot;) %&gt;% 
	hc_chart(zoomType = &quot;xy&quot;) %&gt;% 
	hc_xAxis(title = list(text = &quot;Number of Completed Courses&quot;)) %&gt;% 
   	hc_yAxis(title = list(text = &quot;Number of Students&quot;), max = 35000) %&gt;% 
   	hc_legend(enabled = FALSE)

fig5</code></pre>
<p><img src="figure5.png" alt="Bar graph showing the number of courses completed per student. The vast majority of students only complete one class." /><br />
</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>Wow! There’s a few things to point out here:</p>
<ul>
<li>The highest number of students (33,563 or 33% of students) completed only between 1 and 5 courses.</li>
<li>The highest number of courses completed is 775! Since we’re only looking at 344 courses here, that’s a bit surprising. That student would have needed to complete almost every course twice! Is that the only student who has taken courses more than once?</li>
</ul>
<pre class="r"><code>multi_class &lt;- student_courses %&gt;% 
			filter(count &gt; 344)

nrow(multi_class)</code></pre>
<pre><code>## [1] 219</code></pre>
<p>219 students have taken more than the offered 344 courses and thus must have repeated some! It’s possible that the other students have repeated some courses too. I’ll come back to <a href="#which-courses-tend-to-be-repeated-by-students">that</a>.</p>
</div>
<div id="can-you-group-students-based-on-the-number-of-classes-they-take-vs.-the-amount-of-time-they-spend-per-class" class="section level3">
<h3>Can you group students based on the number of classes they take vs. the amount of time they spend per class?</h3>
<p>The FCC folks who released this dataset seem interested in ways to group their students. I’m curious if this can be done by looking at the number of courses students have completed in comparison to the amount of time spent per course. Do students who complete classes more quickly tend to burn out quickly and ultimately take fewer courses?</p>
<pre class="r"><code>student_courses2 &lt;- student_courses %&gt;% 
		filter(count &gt; 1)


ggplot(student_courses2, aes(x = count, y = median_time)) + geom_point(alpha = 1/4) + 
    labs(x = &quot;Number of Completed Courses&quot;, y = &quot;Average time per Course (minutes)&quot;)</code></pre>
<p><img src="unnamed-chunk-44-1.png" alt="Scatter plot showing the average time per course against the number of courses completed. Students who take a very long time completing courses, tend to complete very few." /><br />
</p>
<p>This figure is a little overwhelmed with outliers who spent a very long time completing few courses.</p>
<p>I’d like to see what this looks like if students don’t take breaks between classes, so I’m going to remove any entries where the time to complete the course was greater than 14 days.</p>
<pre class="r"><code>student_no_break &lt;- sc_full4 %&gt;% 
		filter(overallnum &gt; 5) %&gt;% group_by(.id) %&gt;% 
    		mutate(time = as.numeric(time_since_last, units = &quot;mins&quot;)) %&gt;% 
    		summarise(count = n(), total_time = sum(time, na.rm = TRUE), 
        			median_time = median(time, na.rm = TRUE), 
			average_time = mean(time, na.rm = TRUE), 
			max_time = max(time, na.rm = TRUE)) %&gt;% 
    		filter(count &gt; 1, max_time &lt; 20160) %&gt;% 
		mutate(time_per_class = (total_time/count))

ggplot(student_no_break, aes(x = count, y = average_time)) + 
    geom_point(alpha = 1/4) + labs(x = &quot;Number of Completed Courses&quot;, 
    y = &quot;Average time per Course (minutes)&quot;)</code></pre>
<p><img src="unnamed-chunk-45-1.png" alt="Zoomed-in Scatter plot showing the average time per course against the number of courses completed. Students who take a very long time completing courses, tend to complete very few." /><br />
</p>
<p>Generally speaking, it looks like students who complete courses quickly (not including any breaks) complete the most courses overall. But what if we take breaks into account?</p>
</div>
<div id="does-taking-a-2-week-break-help-or-hurt-course-completion" class="section level3">
<h3>Does taking a 2 week break help or hurt course completion?</h3>
<p>I wanted to look at a box plot of course completion depending on the number of breaks students completed.</p>
<pre class="r"><code>total_breaks &lt;- sc_full4 %&gt;% 
		group_by(.id) %&gt;% 
		mutate(time = as.numeric(time_since_last, units = &quot;mins&quot;)) %&gt;% 
		summarise(breaks = length(.id[time &gt; 20160])) %&gt;% 
		mutate(breaks = breaks - 1) %&gt;% 
		ungroup()

breaks &lt;- left_join(total_breaks, student_courses, by = &quot;.id&quot;)

multi_class_breaks &lt;- breaks %&gt;% 
		filter(count &gt; 1)


fig6 &lt;- highchart() %&gt;% 
		hc_add_series_boxplot(multi_class_breaks$count, multi_class_breaks$breaks) %&gt;% 	
		hc_xAxis(title = list(text = &quot;Number of &gt; 14 Day Breaks&quot;)) %&gt;% 
    		hc_yAxis(title = list(text = &quot;Number of Completed Courses&quot;), 
        			max = 500)

fig6</code></pre>
<p><img src="figure6.png" alt="Box and whisker plot showing the number of 2 week or more breaks against the number of completed courses." /><br />
</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>It seems possible that taking one or more 2 week breaks from the FCC program may actually have a positive impact on the number of courses completed. However, it is unclear at this time if any of those courses are repeats. Let’s try to take out repeat courses.</p>
<pre class="r"><code>no_repeats &lt;- sc_full4 %&gt;% 
	group_by(.id) %&gt;% 
	distinct(course) %&gt;% 
    	summarise(nr_count = n()) %&gt;% 
	ungroup()



no_repeat_join &lt;- left_join(no_repeats, breaks, by = &quot;.id&quot;)

nr_multi &lt;- no_repeat_join %&gt;% filter(nr_count &gt; 1)


fig7 &lt;- highchart() %&gt;% 
	hc_add_series_boxplot(nr_multi$nr_count, nr_multi$breaks) %&gt;% 
	hc_xAxis(title = list(text = &quot;Number of &gt; 14 Day Breaks&quot;)) %&gt;% 
    	hc_yAxis(title = list(text = &quot;Number of Completed Courses (Without Repeats)&quot;), 
        			max = 300, 
			min = 0)

fig7</code></pre>
<iframe seamless src="https://raw.githubusercontent.com/ProQuestionAsker/ProQuestionAsker.github.io/fc77f89e9108750a8af8dadca66d8f833cef39cb/content/projects/FCC_Courses_files/figure-markdown_github/fig7.html
" width="100%" height="500" id="iframe_container">
</iframe>
<p><img src="figure7.png" alt="Bar graph showing the number of courses completed per student. The vast majority of students only complete one class." /><br />
</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>Even taking repeated courses out of the dataset seems to indicate that of students who completed more than one course, the presence of one or more 2 week breaks actually increases the median number of courses that will be completed. It may be worth encouraging students to take short breaks between classes if they feel they need to.</p>
</div>
<div id="which-courses-tend-to-be-repeated-by-students" class="section level3">
<h3>Which courses tend to be repeated by students?</h3>
<pre class="r"><code>repeats &lt;- sc_full4 %&gt;% 
	group_by(.id, section, overallnum, course) %&gt;% 
    	summarise(course_count = n()) %&gt;% 
	ungroup() %&gt;% 
	group_by(overallnum, section, course) %&gt;% 
	summarise(student_repeats = n(), 
		avg_repeats = mean(course_count)) %&gt;% 
    	arrange(overallnum)


fig8 &lt;- hchart(repeats, &quot;column&quot;, x = course, y = avg_repeats, color = section) %&gt;% 
	hc_title(text = &quot;Average Number of Times a Single Student Completed Each Course&quot;) %&gt;% 
    	hc_subtitle(text = &quot;&lt;i&gt;In course curriculum order&lt;/i&gt;&quot;) %&gt;% 
    	hc_xAxis(title = list(text = &quot;FCC Course (in order of FCC course curriculum)&quot;)) %&gt;% 
    	hc_yAxis(title = list(text = &quot;Mean # Times Single Student Completed Each Course&quot;), 
       		max = 1.5, min = 1) %&gt;% 
	hc_chart(zoomType = &quot;xy&quot;) %&gt;% 
    	hc_tooltip(headerFormat = &quot;&quot;, pointFormat = &quot;&lt;b&gt;Class: {point.course}&lt;/b&gt; &lt;br&gt;
		Section: {point.section}&lt;br&gt;
		Mean times course taken by single student: {point.y} times&quot;, 
        		valueDecimals = 2)

fig8</code></pre>
<p><img src="figure8.png" alt="Bar graph showing the number of times each student took each course." /> /</p>
<p><em>Note: this figure that was once interactive has now been replaced with a static image. The above interactive code should still work, though if you choose to use it</em></p>
<p>The courses closest to 1 in this figure were repeated the fewest number of times by students. The most commonly repeated course in the entire curriculum was “Where art thou”, a course near the beginning of the “Intermediate Algorithm Scripting” Section.</p>
<p>Generally speaking, sections with the most repeated courses were:</p>
<ul>
<li>Basic JavaScript</li>
<li>Basic Algorithm Scripting</li>
<li>Intermediate Algorithm Scripting</li>
<li>Automated Testing and Debugging</li>
<li>Advanced Algorithm Scripting</li>
</ul>
<p>This could indicate that the courses in these sections are simply more difficult than other sections or that the material in these courses needs to be viewed more than once to completely comprehend the material. Either way, the content in these course sections should be assessed.</p>
</div>
<div id="can-we-predict-the-number-of-courses-a-student-will-complete-using-machine-learning" class="section level3">
<h3>Can we predict the number of courses a student will complete using machine learning?</h3>
<p>I’m going to use some simple machine learning to see if I can predict the number of courses a student will complete (not counting repeated courses). I’m going to include 4 variables in this model:</p>
<ul>
<li>First completed course</li>
<li>Number of repeated courses</li>
<li>Number of 14 day breaks</li>
<li>Median course completion time (not including &gt; 14 day breaks)</li>
</ul>
<p>First, I need to transform my dataset to fit into a frame with the needed variables. To remain consistent, I’ll once again use <code>dplyr</code> functions for this.</p>
<pre class="r"><code>repeat_students &lt;- sc_full4 %&gt;% 
	group_by(.id) %&gt;% 
	summarise(total_count = n()) %&gt;% 
    	ungroup() %&gt;% 
	filter(total_count &gt; 1)

first_course &lt;- sc_full4 %&gt;% 
	group_by(.id) %&gt;% 
	filter(st_cour_num == 1) %&gt;% 
	select(1:2) %&gt;% 
	ungroup()

repeated_courses &lt;- sc_full4 %&gt;% 
	group_by(.id, course) %&gt;% 
	summarise(course_count = n()) %&gt;% 
    	filter(course_count &gt; 1) %&gt;% 
	summarise(repeat_count = n()) %&gt;% 
   	ungroup()

breaks_courses &lt;- sc_full4 %&gt;% 
	group_by(.id) %&gt;% 
	mutate(time = as.numeric(time_since_last, units = &quot;mins&quot;)) %&gt;% 
	summarise(breaks = length(.id[time &gt; 20160])) %&gt;% 
	mutate(breaks = breaks - 1) %&gt;% 
	ungroup()

median_courses &lt;- sc_full4 %&gt;% 
	group_by(.id) %&gt;% 
	mutate(time = as.numeric(time_since_last, units = &quot;mins&quot;)) %&gt;% 
	filter(time &lt; 20160) %&gt;% 
	summarise(median_time = median(time, na.rm = TRUE)) %&gt;% 
	ungroup()

completed_courses &lt;- sc_full4 %&gt;% 
	group_by(.id) %&gt;% 
	distinct(course) %&gt;% 
   	summarise(nr_count = n()) %&gt;% 
	ungroup()

mlset &lt;- left_join(repeat_students, first_course, by = &quot;.id&quot;)
mlset &lt;- left_join(mlset, repeated_courses, by = &quot;.id&quot;)
mlset &lt;- left_join(mlset, breaks_courses, by = &quot;.id&quot;)
mlset &lt;- left_join(mlset, median_courses, by = &quot;.id&quot;)
mlset &lt;- left_join(mlset, completed_courses, by = &quot;.id&quot;)

# Replacing NA in repeat_count column with 0
mlset$repeat_count[is.na(mlset$repeat_count)] &lt;- 0

# Making course into a factor
mlset$course &lt;- as.factor(mlset$course)</code></pre>
<p>Now that the dataframe is set up the way I want (a single row per student and only the variables I’m interested in), I’m going to randomize the dataset and extract a test set.</p>
<pre class="r"><code># Set random seed
set.seed(1)

# Shuffle rows of data set
n &lt;- nrow(mlset)
shuffled &lt;- mlset[sample(n), ]

# Perform 70/30 split (70% to training set, 30% to test set)
train_indices &lt;- 1:round(0.7 * n)
train &lt;- shuffled[train_indices, ]

test_indices &lt;- (round(0.7 * n) + 1):n
test &lt;- shuffled[test_indices, ]</code></pre>
<div id="fitting-a-baseline-model" class="section level4">
<h4>Fitting a baseline model</h4>
<p>Without adding any extra variables, how well can we predict the number of courses that a student will complete? Without any additional variables, my best guess is that the mean number of courses taken (without replication) would help us predict the number of courses completed. This will give us a baseline to compare our more complex models with. Wow a RMSE of 73.17!</p>
<pre class="r"><code># Creating baseline model
baseline &lt;- mean(train$nr_count)

# Evaluate RMSE on the test set
base_test &lt;- sqrt(mean((baseline - test$nr_count)^2))
base_test</code></pre>
<pre><code>## [1] 73.17323</code></pre>
</div>
<div id="creating-traincontrol" class="section level4">
<h4>Creating trainControl</h4>
<p>Since I plan to use the <code>caret</code> package to test two different models for these data, I will create a system that will perform a 10-fold cross-validation of the training dataset.</p>
<pre class="r"><code>myControl &lt;- trainControl(method = &quot;cv&quot;, number = 10, verboseIter = TRUE)</code></pre>
</div>
<div id="fitting-a-random-forest-model" class="section level4">
<h4>Fitting a random forest model</h4>
<p>The first type of model I’d like to use is a random forest model (using the <code>ranger</code> and <code>caret</code> packages and the trainControl object I just created).</p>
<pre class="r"><code>rf_model &lt;- train(nr_count ~ course + repeat_count + breaks + 
    median_time, data = train, tuneLength = 3, method = &quot;ranger&quot;, 
    trControl = myControl, importance = &quot;impurity&quot;)</code></pre>
<pre class="r"><code>rf_model</code></pre>
<pre><code>## Random Forest 
## 
## 55502 samples
##     4 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 49951, 49952, 49952, 49952, 49953, 49951, ... 
## Resampling results across tuning parameters:
## 
##   mtry  RMSE      Rsquared 
##     2   69.16746  0.2839369
##   122   58.47552  0.3601910
##   243   66.00565  0.2475999
## 
## RMSE was used to select the optimal model using  the smallest value.
## The final value used for the model was mtry = 122.</code></pre>
<p>Our model is an OK fit, explaining about 55% of the variation in our model with a RMSE of 49.</p>
</div>
<div id="fitting-a-glmnet-model" class="section level4">
<h4>Fitting a glmnet model</h4>
<p>I’m also going to try to fit a glmnet model to these data.</p>
<pre class="r"><code>glm_model &lt;- train(nr_count ~ course + repeat_count + breaks + 
    median_time, data = train, tuneLength = 3, method = &quot;glmnet&quot;, 
    trControl = myControl)</code></pre>
<pre><code>## Loading required package: glmnet

## Loading required package: Matrix

## 
## Attaching package: &#39;Matrix&#39;

## The following object is masked from &#39;package:tidyr&#39;:
## 
##     expand

## Loading required package: foreach

## Loaded glmnet 2.0-5</code></pre>
<pre class="r"><code>glm_model</code></pre>
<pre><code>## glmnet 
## 
## 55502 samples
##     4 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 49952, 49950, 49952, 49952, 49951, 49952, ... 
## Resampling results across tuning parameters:
## 
##   alpha  lambda      RMSE      Rsquared 
##   0.10   0.05861448  64.27342  0.2272597
##   0.10   0.58614484  64.23881  0.2280560
##   0.10   5.86144844  64.26716  0.2287188
##   0.55   0.05861448  64.25864  0.2276078
##   0.55   0.58614484  64.17347  0.2297203
##   0.55   5.86144844  64.84995  0.2170755
##   1.00   0.05861448  64.23882  0.2280713
##   1.00   0.58614484  64.21272  0.2288975
##   1.00   5.86144844  65.07230  0.2166004
## 
## RMSE was used to select the optimal model using  the smallest value.
## The final values used for the model were alpha = 0.55 and lambda
##  = 0.5861448.</code></pre>
<p>The best glmnet model explained about 48% of the variance in our dataset with a RMSE of about 53.</p>
</div>
<div id="comparing-model-fit" class="section level4">
<h4>Comparing Model Fit</h4>
<pre class="r"><code># Create a list of models
models &lt;- list(rf = rf_model, glmnet = glm_model)

# Resample the models
resampled &lt;- resamples(models)

# Generate a summary
summary(resampled)</code></pre>
<pre><code>## 
## Call:
## summary.resamples(object = resampled)
## 
## Models: rf, glmnet 
## Number of resamples: 10 
## 
## RMSE 
##         Min. 1st Qu. Median  Mean 3rd Qu.  Max. NA&#39;s
## rf     57.79   57.91  58.52 58.48   58.85 59.50    0
## glmnet 63.36   64.06  64.27 64.17   64.34 64.75    0
## 
## Rsquared 
##          Min. 1st Qu. Median   Mean 3rd Qu.   Max. NA&#39;s
## rf     0.3312  0.3510 0.3629 0.3602  0.3724 0.3781    0
## glmnet 0.2204  0.2258 0.2268 0.2297  0.2317 0.2487    0</code></pre>
<pre class="r"><code># Plot the differences between model fits
dotplot(resampled, metric = &quot;RMSE&quot;)</code></pre>
<p><img src="unnamed-chunk-60-1.png" alt="Dot plot showing the glmnet model is more accurate than the random forest model" /><br />
</p>
<pre class="r"><code>dotplot(resampled, metric = &quot;Rsquared&quot;)</code></pre>
<p><img src="unnamed-chunk-60-2.png" alt="Dot plot showing the random forest model is more accurate than the glmnet model" /><br />
</p>
<p>So our Random Forest model has a better fit and a lower error than the glmnet model. Let’s see which predictors were the most important to that model.</p>
<pre class="r"><code># Creating a Variable Importance variable
vimp &lt;- varImp(rf_model)

# Plotting &#39;vimp&#39;
ggplot(vimp, top = 20[1])</code></pre>
<p><img src="unnamed-chunk-61-1.png" alt="Bar graph showing the factors that influenced the model the most: largely the repeat count and median time to complete each course followed by the breaks taken by the student" /><br />
</p>
<p>The median time spent on each class is the most important variable in our current model, followed by the first course in the series, and the number of courses that were repeated.</p>
</div>
</div>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>While I didn’t answer every one of the questions that FCC was interested in, I was able to answer a few, and here’s what I found:</p>
<ul>
<li><strong>Starting Location</strong> : While users start their FCC journey at a few different places, most begin at either “Learn how Free Code Camp works” and “Say Hello to HTML Elements”.</li>
<li><strong>Most Popular Courses</strong> : The courses offered early in the curriculum were completed mre frequently, and course completion drops off throughout the “HTML5 and CSS” and “Responsive Design with Bootstrap” sections.</li>
<li><strong>Longest Courses to Complete</strong> : The courses that took the longest (on average) to complete were:
<ul>
<li>Claim Your Backend Development Certificate (6845 minutes or 4.75 days)</li>
<li>Build a Voting App (6675 minutes or 4.6 days)</li>
<li>Build a Nightlife Coordination App (4861 minutes or 3.4 days)</li>
<li>Use the Twitchtv JSON API (4289 minutes or 3 days)</li>
<li>Build a Simon Game (4280 minutes or 3 days)</li>
</ul></li>
<li><strong>Course Completion</strong> : About 1/3 of students only complete between 1 and 5 courses.</li>
<li><strong>Repeated Course Completion</strong> : Many students complete the same course more than once. The most commonly repeated courses are:
<ul>
<li>Basic JavaScript</li>
<li>Basic Algorithm Scripting</li>
<li>Intermediate Algorithm Scripting</li>
<li>Automated Testing and Debugging</li>
<li>Advanced Algorithm Scripting</li>
</ul></li>
<li><strong>Taking Two Week Breaks</strong> : Taking one or more two week breaks actually appears to lead to a higher median number of completed courses.</li>
<li><strong>Student Flow Through Course Map</strong> : Users tend to take many of the completed courses in the recommended order, but some suggested pathways are ignored in favor of more user-preferred pathways. Several courses don’t appear to fit into the typical flow of the course curriculum. These courses seem to be treated as stand-alone courses:
<ul>
<li>Courses in the Node.js and Express.js section</li>
<li>“Get Set for Basejumps”</li>
<li>“Save your code revisions forever with Git”</li>
<li>Courses in the Dynamic Web application section</li>
</ul></li>
<li><strong>Predicting Course Completion</strong> : While a model could be fit, more information is needed to properly predict course completion for FCC students.</li>
</ul>
</div>
<div id="my-suggestions" class="section level2">
<h2>My Suggestions</h2>
<p>While I can only offer suggestions based on the data I am given, I suggest that FCC:</p>
<ul>
<li>Investigate “Line up Form Elements Responsively with Bootstrap” course. Almost 11,000 students complete this course but don’t continue to the next courses in the section.</li>
<li>Determine why the longest courses to complete take so long. Are these courses just unlikely to be completed in one sitting? Are they significantly more difficult than other courses in the curriculum?</li>
<li>Suggest to students that it is OK (and even sometimes helpful) to take a break and then come back. Though, it may be helpful to remind them to come back if they’ve been gone for more than 2 weeks.</li>
<li>Determine why some courses were taken repeatedly by the same students. Is the course material in these courses harder and thus needed to be taken multiple times to comprehend?</li>
<li>Integrate the “stand-alone” courses into the curriculum map in a more cohesive way.</li>
<li>Offer different maps based on students’ end-goal. All courses may not be necessary for each type of student.</li>
</ul>
<p>As always, I appreciate any and all feedback on my work, so feel free to let me know what you think!</p>
</div>
